Repository uprm-inso4116-2025-2026-s1/semester-project-uprm-hand_me_down_clothing, pull requests merged in 2025-10, with the labels that each got.

#150 Sell Piece Page
  source_code/app/globals.css
  source_code/app/listings/sell_piece/page.tsx
  source_code/app/page.tsx
  source_code/package-lock.json
  source_code/package.json
Labels: task: development, state: waiting-for-manager, team 3

#171 Donate page wireframe
  source_code/app/listings/donate_piece/page.tsx
  source_code/app/page.tsx
Labels: task: development, state: waiting-for-manager, team 3

#200 Item upload flowchart
  docs/sections/section2/subsections/2.3.1.adoc
  docs/sections/section2/subsections/section-images/HandMeDown_ItemUpload.png
Labels: state: waiting-for-manager, team 3, task: documentation

#206 Footer Implementation
  source_code/app/layout.tsx
  source_code/package-lock.json
  source_code/package.json
  source_code/public/images/LinkedIn.png
  source_code/public/images/discord.png
  source_code/public/images/fb.png
  source_code/public/images/ig.png
  source_code/public/images/logo.png
  source_code/src/components/Footer.tsx
  source_code/tsconfig.json
Labels: state: waiting-for-manager
